### ISSUE TITLE
Request the code

### ISSUE THREAD

**Issue by woodwm** [ZhongxiaYan/mixed_autonomy_intersections#1]
Hi, 

Your paper on ITSC 2021 is published online at https://ieeexplore.ieee.org/document/9565000.

Are you ready to release the code? Thanks.

**Comment by ZhongxiaYan** [comment]
Hey, thanks for the interest and sorry about the delay. I will release the code within the next two weeks.

**Comment by daweidavidwang** [comment]
Will the code be released this week?? I am also following your fantastic work!

**Comment by ZhongxiaYan** [comment]
Working on a submission this week and traveling this weekend, so probably sometimes next week :-/ Thanks for you guys' interest!

**Comment by ZhongxiaYan** [comment]
Thanks again for your interest and sorry for the delay. I've pushed the code, instructions, videos, and checkpoints now!
