### ISSUE TITLE
The memory is increasing with steps...

### ISSUE THREAD

**Issue by Jeffrey28** [ZhongxiaYan/mixed_autonomy_intersections#10]
![image](https://user-images.githubusercontent.com/26816785/199553910-62b093e2-c81c-4437-8184-25687dbed646.png)
Memory grows gradually with training, which previously led to memory overflow.
The memory value is recored from step 130 to step 200.

**Comment by ZhongxiaYan** [comment]
Yep I know. Like I said, it's a Ray issue. Some memory leaks
