### ISSUE TITLE
 'GridExp' object has no attribute 'wb'

### ISSUE THREAD

**Issue by jiawweiL** [ZhongxiaYan/mixed_autonomy_intersections#3]
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def randint(low, high=None, size=None, dtype=onp.int):  # pylint: disable=missing-function-docstring
i 180 | klcoef 0 | lr 0.001
Traceback (most recent call last):
  File "/home/amax/Users/ljw/mixed_autonomy_intersections/u.py", line 549, in __getattr__
    return self[key]
KeyError: 'wb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "intersection.py", line 312, in <module>
    c.run()
  File "/home/amax/Users/ljw/mixed_autonomy_intersections/exp.py", line 359, in run
    c.train()
  File "/home/amax/Users/ljw/mixed_autonomy_intersections/exp.py", line 289, in train
    c.on_step_start()
  File "/home/amax/Users/ljw/mixed_autonomy_intersections/exp.py", line 164, in on_step_start
    c.log_stats(dict(**stats, **c._alg.on_step_start(), lr=lr))
  File "/home/amax/Users/ljw/mixed_autonomy_intersections/exp.py", line 112, in log_stats
    if c.wb:
  File "/home/amax/Users/ljw/mixed_autonomy_intersections/u.py", line 551, in __getattr__
    self.__getattribute__(key)
AttributeError: 'GridExp' object has no attribute 'wb'

**Comment by ZhongxiaYan** [comment]
Thanks for letting me know. I've fixed that here and committed it to main. https://github.com/ZhongxiaYan/mixed_autonomy_intersections/commit/38d2e3f5d55c837830a8c5e935d8a40e294966b5

In the future, it would be useful for the developer to also provide what command you're using

**Comment by jiawweiL** [comment]
Thank you very much for your reply and the problem has been solved. However, there is another problem here. Is it related to my sumo version





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhongxiaYan/mixed_autonomy_intersections"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月16日(星期四) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhongxiaYan/mixed_autonomy_intersections]  'GridExp' object has no attribute 'wb' (Issue #3)





 
Thanks for letting me know. I've fixed that here and committed it to main. 38d2e3f
 
In the future, it would be useful for the developer to also provide what command you're using

**Comment by ZhongxiaYan** [comment]
What problem are you referring to?
