### ISSUE TITLE
Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"

### ISSUE THREAD

**Issue by Jeffrey28** [ZhongxiaYan/mixed_autonomy_intersections#9]

**Comment by Jeffrey28** [comment]
E1030 23:33:13.840035920 3405685 chttp2_transport.cc:1103]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"

**Comment by ZhongxiaYan** [comment]
I haven't seen this issue before

**Comment by Jeffrey28** [comment]
The program gets stuck or breaks during training. The memory is with 128G. However it has taking more than 48 hours to train it but still in the step 137. The total time used in your training is almost 24 hours. Maybe a better GPU is needed.

**Comment by ZhongxiaYan** [comment]
What GPU is yours? I'm using a NVIDIA V100. You mean your CPU memory is
128G right (not GPU memory)?

**Comment by Jeffrey28** [comment]
Yes, these two are older versions of the GPU (Titan X pascal) with 12G, which cannot be used to train the agents. The V100 has large memory with 32G.

**Comment by Jeffrey28** [comment]
![image](https://user-images.githubusercontent.com/26816785/199394027-b39fe586-448f-4588-a8f9-0e498521ef8f.png)
why can not it use multiple GPUs?

**Comment by ZhongxiaYan** [comment]
I didn't set the infrastructure up for multiple. You'd have to implement
that yourself

**Comment by Jeffrey28** [comment]
Thank you, I will try that.
